- name: Install Logstash
  apt:
    name: logstash
    state: present

- name: Copy Logstash configuration
  template:
    src: logstash.conf.j2
    dest: /etc/logstash/conf.d/logstash.conf
    owner: root
    group: root
    mode: 0644

- name: Start and enable Logstash service
  systemd:
    name: logstash
    enabled: yes
    state: started
