- name: Install Elasticsearch
  apt:
    name: elasticsearch
    state: present

- name: Copy Elasticsearch configuration
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
    owner: elasticsearch
    group: elasticsearch
    mode: 0644

- name: Start and enable Elasticsearch service
  systemd:
    name: elasticsearch
    enabled: yes
    state: started
